# Generated by Django 3.1.2 on 2020-10-31 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pymes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='pyme',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Pymes.pyme'),
            preserve_default=False,
        ),
    ]
