# Generated by Django 3.1.2 on 2020-10-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pymes', '0002_producto_pyme'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='img',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
