# Generated by Django 3.1.2 on 2020-10-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pymes', '0003_cat_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pyme',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
