# Generated by Django 3.1.2 on 2020-11-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pymes', '0005_auto_20201111_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='img',
            field=models.ImageField(upload_to='categorias'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='img',
            field=models.ImageField(upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='pyme',
            name='img',
            field=models.ImageField(upload_to='Pymes'),
        ),
    ]
