# Generated by Django 3.1.2 on 2020-11-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pymes', '0006_auto_20201112_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyme',
            name='descripcion',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
